import os
import time
import logging
import requests
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

SLIDES_API_BASE = "https://slides.googleapis.com/v1/presentations"
TOKEN_URL = "https://oauth2.googleapis.com/token"

def get_valid_slides_token(client_obj):
    """
    Retrieves a valid Google Slides OAuth access token for the given client.
    Refreshes automatically if expired.
    """
    config = client_obj.google_slides_config or {}
    access_token = config.get("access_token")
    refresh_token = config.get("refresh_token")
    expires_at = config.get("token_expires_at", 0)

    # Return access token if still valid (with 60s buffer)
    if access_token and time.time() < (expires_at - 60):
        return access_token

    if not refresh_token:
        raise ValueError("Google Slides refresh token missing. Please re-authenticate.")

    client_id = os.getenv("GMAIL_CLIENT_ID")
    client_secret = os.getenv("GMAIL_CLIENT_SECRET")

    payload = {
        "client_id": client_id,
        "client_secret": client_secret,
        "refresh_token": refresh_token,
        "grant_type": "refresh_token",
    }

    resp = requests.post(TOKEN_URL, data=payload, timeout=15)
    if resp.status_code != 200:
        logger.error("Failed to refresh Google Slides token: %s", resp.text)
        raise ValueError("Failed to refresh Google Slides access token.")

    token_data = resp.json()
    new_access_token = token_data.get("access_token")
    expires_in = token_data.get("expires_in", 3600)

    config["access_token"] = new_access_token
    config["token_expires_at"] = time.time() + expires_in
    client_obj.google_slides_config = config
    client_obj.save(update_fields=["google_slides_config"])

    return new_access_token


def create_google_presentation(client_obj, title=None, topic=None):
    """
    Creates a new Google Presentation in Google Drive with title slide.
    Returns (presentation_id, presentation_url).
    """
    token = get_valid_slides_token(client_obj)

    if not title:
        biz_name = getattr(client_obj, 'business_name', 'Client') or 'Client'
        title = f"UWOConnect Presentation ({biz_name})"

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    # 1. Create blank presentation
    body = {"title": title}
    resp = requests.post(SLIDES_API_BASE, json=body, headers=headers, timeout=20)
    if resp.status_code not in (200, 201):
        logger.error("Failed to create Google Presentation: %s", resp.text)
        if "SERVICE_DISABLED" in resp.text or "has not been used in project" in resp.text:
            raise ValueError("Google Slides API is disabled in your Google Cloud Console. Please enable Google Slides API.")
        raise ValueError(f"Failed to create Google Presentation: {resp.text}")

    data = resp.json()
    presentation_id = data.get("presentationId")
    presentation_url = f"https://docs.google.com/presentation/d/{presentation_id}/edit"

    # 2. Add slide content if topic provided
    if topic:
        requests_list = [
            {
                "createSlide": {
                    "slideLayoutPath": {
                        "predefinedLayout": "SECTION_HEADER"
                    }
                }
            }
        ]
        requests.post(f"{SLIDES_API_BASE}/{presentation_id}:batchUpdate", json={"requests": requests_list}, headers=headers, timeout=15)

    # 3. Update client config with presentation metadata
    config = client_obj.google_slides_config or {}
    config["default_presentation_id"] = presentation_id
    config["default_presentation_name"] = title
    config["default_presentation_url"] = presentation_url
    config["presentations_created_count"] = config.get("presentations_created_count", 0) + 1
    config["last_sync_time"] = datetime.now(timezone.utc).isoformat()

    recent_presentations = config.get("recent_presentations", [])
    presentation_entry = {
        "presentation_id": presentation_id,
        "title": title,
        "topic": topic or "General Presentation",
        "url": presentation_url,
        "created_at": datetime.now(timezone.utc).isoformat()
    }
    recent_presentations.insert(0, presentation_entry)
    config["recent_presentations"] = recent_presentations[:10]  # keep top 10

    client_obj.google_slides_config = config
    client_obj.save(update_fields=["google_slides_config"])

    return presentation_id, presentation_url


def list_client_presentations(client_obj):
    """
    Returns recent presentations generated by the client.
    """
    config = client_obj.google_slides_config or {}
    return config.get("recent_presentations", [])
