# Generated by Django 5.2.15 on 2026-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='channels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
