# Generated by Django 5.2.15 on 2026-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workflow_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='industry',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
