# Generated by Django 5.2.15 on 2026-07-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_workflow_category_workflow_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bot_paused',
            field=models.BooleanField(default=False),
        ),
    ]
