# Generated by Django 5.2.15 on 2026-07-07 06:07

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('before_value', models.TextField(blank=True, null=True)),
                ('after_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('GROWTH', 'Growth'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial')], default='ACTIVE', max_length=20),
        ),
    ]
