# Generated by Django 5.2.15 on 2026-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_permissions_alter_user_role_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('INTERNAL', 'Internal Note')], max_length=10),
        ),
    ]
