# Generated by Django 5.2.15 on 2026-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contact_is_archived_contact_snoozed_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='white_label_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='white_label_logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='white_label_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
