# Generated by Django 5.2.15 on 2026-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Product'), ('DIGITAL', 'Digital Product'), ('BOOK', 'Book / E-Book'), ('SERVICE', 'Service'), ('OTHER', 'Other')], default='PHYSICAL', max_length=50),
        ),
    ]
