# Generated by Django 5.2.15 on 2026-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='whatsapp_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
