# Generated by Django 5.2.15 on 2026-07-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_client_plan_paymentorder'),
        ('api', '0019_client_whatsapp_config'),
    ]

    operations = [
    ]
