# Generated by Django 5.2.15 on 2026-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_paymentorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gmail_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='gmail_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('GMAIL', 'Gmail')], max_length=20),
        ),
    ]
