# Generated by Django 5.2.15 on 2026-08-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_onedrive_fields'),
        ('api', '0023_client_google_calendar_config_and_more'),
    ]

    operations = [
    ]
