# Generated by Django 5.2.15 on 2026-08-06 09:43

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_client_address_client_google_docs_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(default='BookOpen', max_length=50)),
                ('category', models.CharField(default='General', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_time', models.CharField(default='10 mins', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='google_news_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='google_news_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(default='ChevronRight', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_expandable', models.BooleanField(default=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.guide')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('step_type', models.CharField(choices=[('text', 'Rich Text'), ('code', 'Code Snippet'), ('image', 'Image Screenshot'), ('video', 'Video Tutorial'), ('diagram', 'Flow Diagram'), ('checklist', 'Interactive Checklist'), ('faq', 'FAQ Accordion'), ('warning', 'Warning Alert'), ('tip', 'Pro Tip Alert')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('code_language', models.CharField(blank=True, default='bash', max_length=50, null=True)),
                ('checklist_items', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('is_completable', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.guidesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideProgress',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('bookmarked_sections', models.JSONField(blank=True, default=list)),
                ('last_step_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guide')},
            },
        ),
    ]
