# Generated by Django 5.2.15 on 2026-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_guide_client_google_news_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='outlook_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='outlook_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
