# Generated by Django 5.2.15 on 2026-08-07 09:59

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_campaign_body_campaign_channel_client_zoho_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFollowUp',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_hours', models.IntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='api.campaign')),
                ('followup_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.template')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='SENT', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contact')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.campaignfollowup')),
            ],
            options={
                'unique_together': {('followup', 'contact')},
            },
        ),
    ]
