# Generated by Django 5.2.15 on 2026-08-07 07:17

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_client_outlook_config_client_outlook_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(default='Marketing', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='failed_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fallback_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retry_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sending_mode',
            field=models.CharField(default='IMMEDIATE', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='speed_mode',
            field=models.CharField(default='NORMAL', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_queued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_recipients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_replied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.template'),
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail / Google Workspace'), ('outlook', 'Microsoft 365 / Outlook'), ('exchange', 'Microsoft Exchange'), ('imap', 'Custom IMAP / SMTP')], default='gmail', max_length=30)),
                ('email_address', models.EmailField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAutomationWorkflow',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_keyword', models.CharField(blank=True, default='', max_length=255)),
                ('sender_domain', models.CharField(blank=True, default='', max_length=255)),
                ('has_attachments', models.BooleanField(default=False)),
                ('create_crm_lead', models.BooleanField(default=True)),
                ('send_auto_reply', models.BooleanField(default=True)),
                ('notify_admin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_email_workflows', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_automations', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAutoReplyRule',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('sender_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('keyword_match', models.CharField(blank=True, default='', max_length=255)),
                ('reply_type', models.CharField(choices=[('thank_you', 'Thank You Acknowledgment'), ('ticket', 'Support Ticket Number'), ('brochure', 'Sales Product Brochure'), ('out_of_office', 'Holiday Out of Office'), ('ai_generated', 'AI Generated Reply')], default='thank_you', max_length=30)),
                ('reply_subject', models.CharField(blank=True, default='', max_length=255)),
                ('reply_body', models.TextField()),
                ('attachment_file', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_auto_replies', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('scheduled', 'Scheduled'), ('outbox', 'Outbox'), ('spam', 'Spam'), ('trash', 'Trash'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('important', 'Important'), ('starred', 'Starred'), ('snoozed', 'Snoozed')], default='inbox', max_length=30)),
                ('sender_email', models.EmailField(max_length=255)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_recipients', models.JSONField(blank=True, default=list)),
                ('cc_recipients', models.JSONField(blank=True, default=list)),
                ('bcc_recipients', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('forwarded', 'Forwarded'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='delivered', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('recurring_rule', models.CharField(blank=True, default='', max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('meeting_invite_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.emailaccount')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emails', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='api.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTeamNote',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notes', to='api.emailmessage')),
            ],
        ),
    ]
