# Generated by Django 5.2.15 on 2026-08-10 05:29

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_campaign_attachments_campaign_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='client',
            name='greeting_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_dept', models.CharField(blank=True, max_length=100, null=True)),
                ('call_type', models.CharField(choices=[('VOICE', 'Voice'), ('VIDEO', 'Video')], default='VOICE', max_length=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('duration', models.CharField(default='0s', max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_histories', to='api.client')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
