# Generated by Django 5.2.15 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_campaign_target_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='target_contacts',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='is_starred',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
