# Generated by Django 5.2.15 on 2026-08-11 06:37

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_campaign_target_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCallSession',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('caller', models.CharField(max_length=255)),
                ('caller_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', models.CharField(max_length=255)),
                ('recipient_display', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('call_type', models.CharField(default='VOICE', max_length=10)),
                ('is_video', models.BooleanField(default=False)),
                ('sdp_offer', models.TextField(blank=True, null=True)),
                ('sdp_answer', models.TextField(blank=True, null=True)),
                ('ice_candidates', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('RINGING', 'Ringing'), ('CONNECTED', 'Connected'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='RINGING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
