# Generated by Django 5.2.15 on 2026-08-11 07:37

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_active_call_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayConnection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('linked_key_id', models.CharField(blank=True, max_length=200, null=True)),
                ('linked_key_secret', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('TEST', 'Test Mode'), ('LIVE', 'Live Mode')], default='TEST', max_length=10)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error / Revoked')], default='DISCONNECTED', max_length=20)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_connection', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=200, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_account_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('webhook_event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_payments', to='api.client')),
                ('razorpay_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to='api.razorpayconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
