# Generated by Django 5.2.15 on 2026-08-13 06:35

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_salesdocument_salesdocumentactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_default_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_next_number',
            field=models.IntegerField(default=1001),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id_gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='company_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('order_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('channel', models.CharField(default='WEBSITE', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20)),
                ('invoice_status', models.CharField(choices=[('GENERATED', 'Generated'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('payment_method', models.CharField(default='Razorpay', max_length=50)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('seller_details', models.JSONField(blank=True, default=dict)),
                ('billing_details', models.JSONField(blank=True, default=dict)),
                ('shipping_details', models.JSONField(blank=True, default=dict)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.contact')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.order')),
                ('payment_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.productpayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
