# Generated by Django 5.2.17 on 2026-08-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_campaignfollowup_followuplog'),
        ('api', '0034_client_company_logo_url_client_invoice_default_notes_and_more'),
    ]

    operations = [
    ]
