# Generated by Django 5.2.17 on 2026-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_invoice_secure_token_invoice_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='is_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
