# Generated by Django 5.2.17 on 2026-08-24 08:17

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_teaminvite_is_qr_alter_teaminvite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='channel_access',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChannelAuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(default='Admin', max_length=255)),
                ('channel', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('ACCESS_GRANTED', 'Access Granted'), ('ACCESS_REVOKED', 'Access Revoked'), ('BULK_GRANTED', 'Bulk Access Granted'), ('BULK_REVOKED', 'Bulk Access Revoked'), ('MEMBER_ASSIGNED', 'Member Channel Assigned'), ('MEMBER_REVOKED', 'Member Channel Revoked')], max_length=50)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_audit_logs', to='api.client')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
