# Generated by Django 5.2.15 on 2026-08-26 09:04

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_client_channel_access_client_whatsapp_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('COMMUNICATION', 'Communication Channels'), ('CONNECTORS', 'Productivity & Cloud Connectors'), ('MESSAGING', 'Messaging & Conversations'), ('AI', 'AI & Intelligence'), ('CRM', 'CRM & Leads'), ('SALES', 'Sales, Invoicing & Documents'), ('TEAM', 'Team & Operations'), ('DOCUMENTS', 'Knowledge & Documents'), ('REPORTING', 'Analytics & Reports'), ('SETTINGS', 'Settings & Administration')], db_index=True, default='COMMUNICATION', max_length=50)),
                ('feature_type', models.CharField(choices=[('BOOLEAN', 'Boolean (On / Off)'), ('LIMIT', 'Limit Based (Configurable Count)'), ('USAGE', 'Usage Based (Monthly Quota)'), ('CONNECTOR', 'Connector / Integration'), ('CHANNEL', 'Communication Channel'), ('MODULE', 'Functional Module')], default='BOOLEAN', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DEPRECATED', 'Deprecated')], db_index=True, default='ACTIVE', max_length=20)),
                ('icon', models.CharField(default='Box', max_length=50)),
                ('default_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalConnector',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(choices=[('CORE', 'Core Messaging'), ('MESSAGING', 'Social & Messaging'), ('EMAIL', 'Email & Productivity'), ('STORAGE', 'Cloud Storage'), ('CRM', 'CRM & Pipeline'), ('MEDIA', 'Media & Content'), ('CONNECTOR', 'Other Connector')], default='MESSAGING', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_core', models.BooleanField(default=False)),
                ('icon_key', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('scheduled_live_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(default='Super Admin', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_core', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom'), ('ONE_TIME', 'One Time'), ('NO_BILLING', 'No Billing / Free')], default='MONTHLY', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('plan_type', models.CharField(choices=[('STANDARD', 'Standard Tier'), ('CUSTOM', 'Custom Tailored'), ('AGENCY', 'Agency White-Label'), ('ENTERPRISE', 'Enterprise SLA')], default='STANDARD', max_length=30)),
                ('display_order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanAuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('admin_user', models.CharField(default='Admin', max_length=255)),
                ('plan_name', models.CharField(blank=True, default='', max_length=100)),
                ('feature_name', models.CharField(blank=True, default='', max_length=100)),
                ('client_name', models.CharField(blank=True, default='', max_length=150)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='channelauditlog',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='channelauditlog',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelauditlog',
            name='team_member_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='channelauditlog',
            name='action',
            field=models.CharField(choices=[('GLOBAL_ACTIVATED', 'Global Connector Activated'), ('GLOBAL_DEACTIVATED', 'Global Connector Deactivated'), ('ACCESS_GRANTED', 'Client Access Granted'), ('ACCESS_REVOKED', 'Client Access Revoked'), ('BULK_GRANTED', 'Bulk Access Granted'), ('BULK_REVOKED', 'Bulk Access Revoked'), ('MEMBER_ASSIGNED', 'Member Channel Assigned'), ('MEMBER_REVOKED', 'Member Channel Revoked')], max_length=50),
        ),
        migrations.AlterField(
            model_name='channelauditlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_audit_logs', to='api.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(default='FREE', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='white_label_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='api.plan'),
        ),
        migrations.CreateModel(
            name='ClientConnectorAccess',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_key', models.CharField(db_index=True, max_length=50)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('updated_by', models.CharField(default='Admin', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_accesses', to='api.client')),
            ],
            options={
                'ordering': ['client', 'connector_key'],
                'unique_together': {('client', 'connector_key')},
            },
        ),
        migrations.CreateModel(
            name='ClientFeatureOverride',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('ADD', 'Custom Addition (+)'), ('REMOVE', 'Custom Restriction (-)'), ('LIMIT_OVERRIDE', 'Limit Override')], default='ADD', max_length=20)),
                ('limit_value', models.IntegerField(blank=True, default=None, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feature_overrides', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='api.client')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_overrides', to='api.feature')),
            ],
            options={
                'ordering': ['client', 'feature__category', 'feature__name'],
                'unique_together': {('client', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('limit_value', models.IntegerField(blank=True, default=None, null=True)),
                ('limit_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='api.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='api.plan')),
            ],
            options={
                'ordering': ['plan', 'feature__category', 'feature__name'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='TeamMemberConnectorAccess',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_key', models.CharField(db_index=True, max_length=50)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('updated_by', models.CharField(default='Admin', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_connector_accesses', to='api.client')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client', 'team_member', 'connector_key'],
                'unique_together': {('client', 'team_member', 'connector_key')},
            },
        ),
    ]
